# Generated by Django 4.1.7 on 2024-01-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dell', '0015_remove_dellconfirmationpage_body_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfield',
            options={},
        ),
        migrations.RemoveField(
            model_name='dellcampaignemails',
            name='allow',
        ),
        migrations.RemoveField(
            model_name='dellcampaignemails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='dellcampaignemails',
            name='host',
        ),
        migrations.RemoveField(
            model_name='dellcampaignemails',
            name='password',
        ),
        migrations.RemoveField(
            model_name='dellcampaignemails',
            name='port',
        ),
        migrations.RemoveField(
            model_name='dellcampaignlandings',
            name='allow',
        ),
        migrations.RemoveField(
            model_name='dellcampaignlandings',
            name='email',
        ),
        migrations.RemoveField(
            model_name='dellcampaignlandings',
            name='host',
        ),
        migrations.RemoveField(
            model_name='dellcampaignlandings',
            name='password',
        ),
        migrations.RemoveField(
            model_name='dellcampaignlandings',
            name='port',
        ),
        migrations.AddField(
            model_name='dellcustomemail',
            name='send_to_cc',
            field=models.CharField(blank=True, help_text='Separate email address with ";"', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dellcustomemail',
            name='send_to_co',
            field=models.CharField(blank=True, help_text='Separate email address with ";"', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='max_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='min_length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
