# Generated by Django 4.1.7 on 2024-01-25 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dell', '0016_alter_formfield_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formfield',
            old_name='priority',
            new_name='is_register_unique',
        ),
        migrations.AddField(
            model_name='dellcampaignemails',
            name='allow',
            field=models.BooleanField(default=False, help_text='Check this checkbox to confirm the configuration'),
        ),
        migrations.AddField(
            model_name='dellcampaignemails',
            name='email',
            field=models.CharField(default='alerts@the-8agency.com', max_length=255),
        ),
        migrations.AddField(
            model_name='dellcampaignemails',
            name='host',
            field=models.CharField(default='smtp.gmail.com', help_text='ex: smtp.yourhost.com', max_length=255),
        ),
        migrations.AddField(
            model_name='dellcampaignemails',
            name='password',
            field=models.CharField(default='duMeD5RydVX5EZ', max_length=255),
        ),
        migrations.AddField(
            model_name='dellcampaignemails',
            name='port',
            field=models.IntegerField(default=465, help_text='ex: 465', validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AddField(
            model_name='dellcampaignlandings',
            name='allow',
            field=models.BooleanField(default=False, help_text='Check this checkbox to confirm the configuration'),
        ),
        migrations.AddField(
            model_name='dellcampaignlandings',
            name='email',
            field=models.CharField(default='alerts@the-8agency.com', max_length=255),
        ),
        migrations.AddField(
            model_name='dellcampaignlandings',
            name='host',
            field=models.CharField(default='smtp.gmail.com', help_text='ex: smtp.yourhost.com', max_length=255),
        ),
        migrations.AddField(
            model_name='dellcampaignlandings',
            name='password',
            field=models.CharField(default='duMeD5RydVX5EZ', max_length=255),
        ),
        migrations.AddField(
            model_name='dellcampaignlandings',
            name='port',
            field=models.IntegerField(default=465, help_text='ex: 465', validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='dellcustomemail',
            name='send_to_cc',
            field=models.CharField(blank=True, help_text='Separate email address with ";"', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='dellcustomemail',
            name='send_to_co',
            field=models.CharField(blank=True, help_text='Separate email address with ";"', max_length=60, null=True),
        ),
    ]
